export const tokens = {
  color: {
    bg: '#ffffff',
    surface: '#ffffff',
    border: '#d6d6d0',
    borderStrong: '#0a0a0a',
    text: '#0a0a0a',
    textMuted: '#565656',
    textSubtle: '#8a8a84',
    accent: '#0a0a0a',
    accentText: '#ffffff',
    successBg: '#ecfdf3',
    successBorder: '#bbf7d0',
    successText: '#166534',
    warnBg: '#fffbeb',
    warnBorder: '#fde68a',
    warnText: '#92400e',
    dangerBg: '#fef2f2',
    dangerBorder: '#fecaca',
    dangerText: '#b91c1c',
    infoBg: '#eff6ff',
    infoBorder: '#bfdbfe',
    infoText: '#1d4ed8',
  },
  radius: {
    sm: 0,
    md: 0,
    lg: 0,
    pill: 0,
  },
  space: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 40,
  },
  shadow: {
    card: 'none',
    popup: 'none',
  },
  font: {
    h1: { fontSize: 32, fontWeight: 900, lineHeight: 1.05, margin: 0, letterSpacing: 0, textTransform: 'uppercase' },
    h2: { fontSize: 18, fontWeight: 900, lineHeight: 1.2, margin: 0, letterSpacing: 0, textTransform: 'uppercase' },
    label: { fontSize: 11, fontWeight: 900, color: '#565656', textTransform: 'uppercase', letterSpacing: '0.08em' },
    body: { fontSize: 14, color: '#0a0a0a' },
    bodyMuted: { fontSize: 13, color: '#565656' },
  },
}
