#!/usr/bin/env python3
"""Create a visual GA4 launch summary from the CSV files generated by ga4_report.py."""

from __future__ import annotations

import csv
import html
import json
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
GA4_DIR = ROOT / "exports" / "ga4"
OUT_DIR = GA4_DIR / "visuals"


def read_csv(name: str) -> list[dict[str, str]]:
    path = GA4_DIR / name
    if not path.exists() or path.stat().st_size == 0:
        return []
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def num(row: dict[str, str], key: str) -> float:
    try:
        return float(row.get(key) or 0)
    except ValueError:
        return 0.0


def fmt_int(value: float) -> str:
    return f"{value:,.0f}"


def fmt_pct(value: float) -> str:
    return f"{value * 100:.1f}%"


def escape(value: object) -> str:
    return html.escape(str(value), quote=True)


def clean_label(value: str, max_len: int = 42) -> str:
    value = value or "(blank)"
    if len(value) <= max_len:
        return value
    return value[: max_len - 1] + "…"


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def horizontal_bar_svg(
    title: str,
    rows: list[dict[str, str]],
    label_key: str,
    value_key: str,
    filename: str,
    subtitle: str = "",
    color: str = "#2563eb",
    max_rows: int = 8,
) -> str:
    rows = sorted(rows, key=lambda row: num(row, value_key), reverse=True)[:max_rows]
    width = 980
    left = 260
    right = 90
    top = 72
    row_h = 42
    height = top + max(len(rows), 1) * row_h + 36
    chart_w = width - left - right
    max_value = max([num(row, value_key) for row in rows] or [1])

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="#ffffff"/>',
        f'<text x="24" y="34" font-family="Inter, Arial, sans-serif" font-size="22" font-weight="700" fill="#111827">{escape(title)}</text>',
    ]
    if subtitle:
        parts.append(f'<text x="24" y="56" font-family="Inter, Arial, sans-serif" font-size="13" fill="#6b7280">{escape(subtitle)}</text>')

    if not rows:
        parts.append('<text x="24" y="105" font-family="Inter, Arial, sans-serif" font-size="16" fill="#6b7280">No data</text>')
    for idx, row in enumerate(rows):
        y = top + idx * row_h
        value = num(row, value_key)
        bar_w = 0 if max_value == 0 else value / max_value * chart_w
        label = clean_label(row.get(label_key, ""))
        parts.extend(
            [
                f'<text x="24" y="{y + 24}" font-family="Inter, Arial, sans-serif" font-size="14" fill="#374151">{escape(label)}</text>',
                f'<rect x="{left}" y="{y + 7}" width="{chart_w}" height="24" rx="5" fill="#eef2ff"/>',
                f'<rect x="{left}" y="{y + 7}" width="{bar_w:.1f}" height="24" rx="5" fill="{color}"/>',
                f'<text x="{left + chart_w + 14}" y="{y + 24}" font-family="Inter, Arial, sans-serif" font-size="14" font-weight="700" fill="#111827">{fmt_int(value)}</text>',
            ]
        )
    parts.append("</svg>")
    write(OUT_DIR / filename, "\n".join(parts))
    return f"visuals/{filename}"


def daily_line_svg(rows: list[dict[str, str]]) -> str:
    rows = sorted(rows, key=lambda row: row.get("date", ""))
    width = 980
    height = 340
    left = 58
    right = 28
    top = 68
    bottom = 58
    chart_w = width - left - right
    chart_h = height - top - bottom
    sessions = [num(row, "sessions") for row in rows]
    users = [num(row, "activeUsers") for row in rows]
    max_value = max(sessions + users + [1])

    def points(values: list[float]) -> str:
        if len(values) <= 1:
            return ""
        coords = []
        for idx, value in enumerate(values):
            x = left + idx / (len(values) - 1) * chart_w
            y = top + chart_h - value / max_value * chart_h
            coords.append(f"{x:.1f},{y:.1f}")
        return " ".join(coords)

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="#ffffff"/>',
        '<text x="24" y="34" font-family="Inter, Arial, sans-serif" font-size="22" font-weight="700" fill="#111827">Daily Trend</text>',
        '<text x="24" y="56" font-family="Inter, Arial, sans-serif" font-size="13" fill="#6b7280">Sessions and active users by day</text>',
        f'<line x1="{left}" y1="{top + chart_h}" x2="{left + chart_w}" y2="{top + chart_h}" stroke="#d1d5db"/>',
        f'<line x1="{left}" y1="{top}" x2="{left}" y2="{top + chart_h}" stroke="#d1d5db"/>',
        f'<polyline fill="none" stroke="#2563eb" stroke-width="3" points="{points(sessions)}"/>',
        f'<polyline fill="none" stroke="#16a34a" stroke-width="3" points="{points(users)}"/>',
        f'<text x="{left}" y="{height - 22}" font-family="Inter, Arial, sans-serif" font-size="12" fill="#6b7280">{escape(rows[0].get("date", "")) if rows else ""}</text>',
        f'<text x="{left + chart_w - 64}" y="{height - 22}" font-family="Inter, Arial, sans-serif" font-size="12" fill="#6b7280">{escape(rows[-1].get("date", "")) if rows else ""}</text>',
        f'<text x="{left + chart_w - 185}" y="34" font-family="Inter, Arial, sans-serif" font-size="13" fill="#2563eb">Sessions</text>',
        f'<text x="{left + chart_w - 95}" y="34" font-family="Inter, Arial, sans-serif" font-size="13" fill="#16a34a">Users</text>',
    ]
    for value in [0, max_value / 2, max_value]:
        y = top + chart_h - value / max_value * chart_h
        parts.extend(
            [
                f'<line x1="{left}" y1="{y:.1f}" x2="{left + chart_w}" y2="{y:.1f}" stroke="#f3f4f6"/>',
                f'<text x="24" y="{y + 4:.1f}" font-family="Inter, Arial, sans-serif" font-size="12" fill="#6b7280">{fmt_int(value)}</text>',
            ]
        )
    parts.append("</svg>")
    write(OUT_DIR / "daily_trend.svg", "\n".join(parts))
    return "visuals/daily_trend.svg"


def make_summary_cards(totals: dict[str, float]) -> str:
    cards = [
        ("Active users", fmt_int(totals["activeUsers"])),
        ("New users", f'{fmt_int(totals["newUsers"])} ({fmt_pct(totals["newUsers"] / totals["activeUsers"]) if totals["activeUsers"] else "0.0%"})'),
        ("Sessions", fmt_int(totals["sessions"])),
        ("Engagement rate", fmt_pct(totals["engagedSessions"] / totals["sessions"]) if totals["sessions"] else "0.0%"),
        ("Page views", fmt_int(totals["screenPageViews"])),
        ("Pages / session", f'{totals["screenPageViews"] / totals["sessions"]:.1f}' if totals["sessions"] else "0.0"),
        ("Events", fmt_int(totals["eventCount"])),
        ("Revenue", f'{totals["totalRevenue"]:.2f}'),
    ]
    blocks = []
    for label, value in cards:
        blocks.append(
            f'<div class="card"><div class="label">{escape(label)}</div><div class="value">{escape(value)}</div></div>'
        )
    return "\n".join(blocks)


def top_sum(rows: Iterable[dict[str, str]], key: str, metric: str) -> dict[str, float]:
    result: dict[str, float] = {}
    for row in rows:
        result[row.get(key, "(blank)") or "(blank)"] = result.get(row.get(key, "(blank)") or "(blank)", 0) + num(row, metric)
    return result


def main() -> None:
    daily = read_csv("daily_overview.csv")
    sources = read_csv("traffic_sources.csv")
    landings = read_csv("landing_pages.csv")
    pages = read_csv("pages.csv")
    devices = read_csv("devices.csv")
    countries = read_csv("geo_countries.csv")
    events = read_csv("events.csv")

    totals = {
        "activeUsers": sum(num(row, "activeUsers") for row in daily),
        "newUsers": sum(num(row, "newUsers") for row in daily),
        "sessions": sum(num(row, "sessions") for row in daily),
        "engagedSessions": sum(num(row, "engagedSessions") for row in daily),
        "screenPageViews": sum(num(row, "screenPageViews") for row in daily),
        "eventCount": sum(num(row, "eventCount") for row in daily),
        "totalRevenue": sum(num(row, "totalRevenue") for row in daily),
    }

    source_chart = horizontal_bar_svg(
        "Traffic Sources",
        sources,
        "sessionSourceMedium",
        "sessions",
        "traffic_sources.svg",
        "Sessions by source / medium",
        "#2563eb",
    )
    landing_chart = horizontal_bar_svg(
        "Landing Pages",
        landings,
        "landingPagePlusQueryString",
        "sessions",
        "landing_pages.svg",
        "Sessions by first page",
        "#7c3aed",
    )
    pages_chart = horizontal_bar_svg(
        "Top Pages",
        pages,
        "pagePathPlusQueryString",
        "screenPageViews",
        "top_pages.svg",
        "Page views by path",
        "#059669",
    )
    country_chart = horizontal_bar_svg(
        "Countries",
        countries,
        "country",
        "sessions",
        "countries.svg",
        "Sessions by country",
        "#dc2626",
    )
    event_chart = horizontal_bar_svg(
        "Events",
        events,
        "eventName",
        "eventCount",
        "events.svg",
        "Event counts",
        "#ea580c",
    )
    device_rows = [
        {"device": f'{row.get("deviceCategory")} / {row.get("browser")}', "sessions": row.get("sessions", "0")}
        for row in devices
    ]
    device_chart = horizontal_bar_svg(
        "Devices And Browsers",
        device_rows,
        "device",
        "sessions",
        "devices.svg",
        "Sessions by device category and browser",
        "#0891b2",
    )
    daily_chart = daily_line_svg(daily)

    event_counts = {row.get("eventName", ""): num(row, "eventCount") for row in events}
    form_rate = event_counts.get("form_submit", 0) / event_counts.get("form_start", 1) if event_counts.get("form_start") else 0
    admin_views = sum(num(row, "screenPageViews") for row in pages if row.get("pagePathPlusQueryString", "").startswith("/admin"))
    service_sessions = sum(num(row, "sessions") for row in sources if row.get("sessionSourceMedium") in {"vercel.com / referral", "tagassistant.google.com / referral"})
    instagram_sessions = sum(num(row, "sessions") for row in sources if "instagram" in row.get("sessionSourceMedium", "") or row.get("sessionSourceMedium") == "ig / social")

    insights = [
        f"GA4 is now reading the correct property `535291350`; the site stream is `G-CMVZYXVZ8Y`.",
        f"Topline is modest but real: {fmt_int(totals['activeUsers'])} active users, {fmt_int(totals['sessions'])} sessions, {fmt_int(totals['screenPageViews'])} page views.",
        f"Engagement is healthy overall: {fmt_pct(totals['engagedSessions'] / totals['sessions']) if totals['sessions'] else '0.0%'} engaged sessions and {totals['screenPageViews'] / totals['sessions']:.1f} pages/session.",
        f"Instagram is already a major acquisition channel: {fmt_int(instagram_sessions)} sessions across `l.instagram.com` and `ig / social`, roughly {fmt_pct(instagram_sessions / totals['sessions']) if totals['sessions'] else '0.0%'} of sessions.",
        f"The dataset is polluted by internal/service traffic: `/admin/*` accounts for {fmt_int(admin_views)} page views, and Vercel/Tag Assistant contribute {fmt_int(service_sessions)} sessions.",
        f"`/maintenance` still appears as a meaningful landing page with 21 sessions and weak engagement, which likely reflects launch/testing residue.",
        "GA4 ecommerce events are absent: no `view_item`, `add_to_cart`, `begin_checkout`, or `purchase`, so product funnel reporting is currently blind.",
        f"Forms are being started but rarely submitted: {fmt_int(event_counts.get('form_start', 0))} `form_start` vs {fmt_int(event_counts.get('form_submit', 0))} `form_submit` ({fmt_pct(form_rate)}).",
    ]

    charts = [daily_chart, source_chart, landing_chart, pages_chart, device_chart, country_chart, event_chart]
    html_doc = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>GA4 Visual Summary</title>
  <style>
    body {{ font-family: Inter, Arial, sans-serif; margin: 0; background: #f8fafc; color: #111827; }}
    main {{ max-width: 1120px; margin: 0 auto; padding: 36px 24px 56px; }}
    h1 {{ margin: 0 0 6px; font-size: 34px; }}
    .meta {{ color: #6b7280; margin-bottom: 24px; }}
    .cards {{ display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 12px; margin: 20px 0 28px; }}
    .card {{ background: white; border: 1px solid #e5e7eb; border-radius: 8px; padding: 14px 16px; }}
    .label {{ color: #6b7280; font-size: 12px; text-transform: uppercase; letter-spacing: .04em; }}
    .value {{ margin-top: 8px; font-weight: 760; font-size: 25px; }}
    .grid {{ display: grid; grid-template-columns: 1fr; gap: 16px; }}
    .panel {{ background: white; border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px; overflow: auto; }}
    .insights {{ background: white; border: 1px solid #e5e7eb; border-radius: 8px; padding: 18px 22px; margin-bottom: 24px; }}
    .insights li {{ margin: 8px 0; line-height: 1.45; }}
    img {{ max-width: 100%; display: block; }}
  </style>
</head>
<body>
<main>
  <h1>GA4 Visual Summary</h1>
  <div class="meta">Property 535291350 · 2026-05-01 to 2026-05-17 · Stream G-CMVZYXVZ8Y</div>
  <section class="cards">
    {make_summary_cards(totals)}
  </section>
  <section class="insights">
    <h2>Main Insights</h2>
    <ul>
      {''.join(f'<li>{escape(item)}</li>' for item in insights)}
    </ul>
  </section>
  <section class="grid">
    {''.join(f'<div class="panel"><img src="{escape(chart)}" alt=""></div>' for chart in charts)}
  </section>
</main>
</body>
</html>
"""
    write(GA4_DIR / "visual_summary.html", html_doc)

    markdown = [
        "# GA4 Visual Summary",
        "",
        "Property: `535291350`  ",
        "Date range: `2026-05-01` to `2026-05-17`  ",
        "Stream: `G-CMVZYXVZ8Y`",
        "",
        "## KPI Snapshot",
        "",
        f"- Active users: **{fmt_int(totals['activeUsers'])}**",
        f"- New users: **{fmt_int(totals['newUsers'])}**",
        f"- Sessions: **{fmt_int(totals['sessions'])}**",
        f"- Engagement rate: **{fmt_pct(totals['engagedSessions'] / totals['sessions']) if totals['sessions'] else '0.0%'}**",
        f"- Page views: **{fmt_int(totals['screenPageViews'])}**",
        f"- Pages/session: **{totals['screenPageViews'] / totals['sessions']:.1f}**" if totals["sessions"] else "- Pages/session: **0.0**",
        f"- Events: **{fmt_int(totals['eventCount'])}**",
        f"- Revenue: **{totals['totalRevenue']:.2f}**",
        "",
        "## Main Insights",
        "",
        *[f"- {item}" for item in insights],
        "",
        "## Charts",
        "",
        *[f"![{Path(chart).stem}]({chart})" for chart in charts],
        "",
    ]
    write(GA4_DIR / "visual_summary.md", "\n".join(markdown))
    write(GA4_DIR / "visual_summary_data.json", json.dumps({"totals": totals, "insights": insights}, indent=2),)

    print(f"Wrote {GA4_DIR / 'visual_summary.html'}")
    print(f"Wrote {GA4_DIR / 'visual_summary.md'}")


if __name__ == "__main__":
    main()
